### ISSUE TITLE
Auter waits forever for yum locks

### ISSUE THREAD

**Issue by Alibloke** [rackerlabs/auter#101]
If there's a yum lock, auter will wait forever until the lock is removed.  This could have the unintended consequence of an update out of schedule, worse an automatic post update reboot out of schedule (if enabled).

Steps to reproduce:
* Create a yum lock by starting a yum upgrade and leave it at the prompt
* Let Auter to run via cron
* Auter will wait for the lock to be removed
* Exit out of the yum upgrade some time later
* Auter will apply all updates (and reboot if set) out of schedule

**Comment by reaperzn** [comment]
Done
