### ISSUE TITLE
Rotate should delete any left-over high-number files 

### ISSUE THREAD

**Issue by Pingue** [rackerlabs/auter#110]
It could be relevant to include all files numbered above ROTATE, to avoid left-overs when modifying the value.

Ex:
```
if [[ -e "${OUTPUT_FILE}.${ROTATE}" ]]; then
  ROTATE_MAX_FOUND=$(ls -1 ${OUTPUT_FILE}.* | tail -n 1 | sed 's/.*\([0-9]\{1,\}\)$/\1/' )
  for i in `seq ${ROTATE} 1 ${ROTATE_MAX_COUNT}`; do
    [[ -e  "${OUTPUT_FILE}.$i" ]] && rm -f "${OUTPUT_FILE}.$i"
  done
fi
```

ie if ROTATE is initially set to 10 and then decreased to 5, we should delete the 6th-though-10th files, so we don't have old runs lying around

**Comment by reaperzn** [comment]
New PR for this request: #146

**Comment by reaperzn** [comment]
This has now been completed in #146
