### ISSUE TITLE
Review shellcheck default exclusions in 05-shellcheck.sh

### ISSUE THREAD

**Issue by rhodesn** [rackerlabs/auter#163]
I was wondering why a couple of the default exclusions are in place:
- [SC2102](https://github.com/koalaman/shellcheck/wiki/SC2102): does not exist 
- [SC2123](https://github.com/koalaman/shellcheck/wiki/SC2124): seems quite legitimate considering how much we use arrays for command arguments etc
- [SC2155](https://github.com/koalaman/shellcheck/wiki/SC2155): I think this one can be left in, however prior to submitting pull requests this should be checked via a manual run of shellcheck
- [SC2148](https://github.com/koalaman/shellcheck/wiki/SC2148): why don't we include shebangs in auter.yumdnfModule and auter.aptModule? I know they are not stand-alone scripts, but I can't see a downside to including it; it would also mean shellcheck/syntax highlighting work without any additional faffing. 
- [SC2044](https://github.com/koalaman/shellcheck/wiki/SC2044): not sure why this is being ignored - it seems simple to fix any loops that we have currently doing this.

**Comment by reaperzn** [comment]
- SC2101 is related to https://github.com/koalaman/shellcheck/issues/682. This was previously removed from the online checker but still exists in the standalone package. 

The rest of the excludes can be removed.

**Comment by nrhodes91** [comment]
Great thanks - I'll get something submitted to remove the other checks.
