### ISSUE TITLE
conditionalReboot does not detect 'outdated' running kernel

### ISSUE THREAD

**Issue by mark-hyde** [rackerlabs/auter#166]
On centos/rhel 6.  if the kernel has been updated outside of an auter run then the conditionalReboot script in the devel branch will not detect that a reboot is required.

https://github.com/rackerlabs/auter/blob/develop/contrib/conditionalReboot/99-conditionalReboot.sh

perhaps add some logic like:
```
if [[ "$(grubby --default-kernel |sed 's#.*vmlinuz-##g')" != "$(uname -r)" ]]
then
  echo reboot needed
else
  echo "we're OK"
fi
```

**Comment by reaperzn** [comment]
Good catch @racker-markh Ill add something in shortly

**Comment by reaperzn** [comment]
Turns out debian/ubuntu dont use these cool tools. I will check if there is a generic tool otherwise I may need to look into parsing the grub.conf which may also be more challenging due to debian allowing a /etc/grub.d directory.

**Comment by mark-hyde** [comment]
It may be that the debian/ubuntu 'needs-rebooting' script catches this case?
I don't have a deb based distro to check this on though.
