### ISSUE TITLE
Release 0.12 - Testing required: RHEL/CentOS 6

### ISSUE THREAD

**Issue by reaperzn** [rackerlabs/auter#173]
This issue has been raised as part of the release process for Version 0.12

Please could auter be fully tested on the OS mentioned in the title of this issue. 

# Notes:
 - Please assign yourself to the issue **ONLY IF** you are actively working on it
 - Please ensure you are testing the code from the **v0.12 branch** of this repo
 - Follow the testing guide from https://github.com/rackerlabs/auter/blob/develop/HACKING.md
 - Any problems should be documented in this issue
 - If there are changes required, after the issue has been validated, a new issue should be raised and linked referenced in this issue

**Comment by Markpayne01** [comment]
Incomplete: 




### Config settings

AUTOREBOOT="no"
ONLYINSTALLFROMPREP="yes"
PREDOWNLOADUPDATES=yes

		[root@autertestcentos6 ~]# cat /etc/redhat-release 
		CentOS release 6.10 (Final)
		[root@autertestcentos6 ~]# 


		[root@autertestcentos6 ~]# egrep '^AUTOREBOOT|^ONLYINSTALLFROMPREP|^PREDOWNLOADUPDATES' /etc/auter/auter.conf 
		AUTOREBOOT="no"
		PREDOWNLOADUPDATES="yes"
		ONLYINSTALLFROMPREP="yes"
		[root@autertestcentos6 ~]# 





### <OS test version>

#### auter status

[ pass ] auter --status
    - Check: /var/lib/auter/enabled exists

			[root@autertestcentos6 ~]# auter --status
			auter is currently enabled and not running
			[root@autertestcentos6 ~]# stat /var/lib/auter/enabled
			  File: `/var/lib/auter/enabled'
			  Size: 119       	Blocks: 8          IO Block: 4096   regular file
			Device: ca01h/51713d	Inode: 786700      Links: 1
			Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
			Access: 2018-07-18 17:00:46.509998763 +0000
			Modify: 2018-07-18 17:00:46.509998763 +0000
			Change: 2018-07-18 17:00:46.509998763 +0000
			[root@autertestcentos6 ~]# 



[ pass ] auter --disable
    - Check: /var/lib/auter/enabled does not exist



			[root@autertestcentos6 ~]# auter --disable
			INFO: auter disabled
			[root@autertestcentos6 ~]# stat /var/lib/auter/enabled
			stat: cannot stat `/var/lib/auter/enabled': No such file or directory
			[root@autertestcentos6 ~]# 
			[root@autertestcentos6 ~]# auter --status
			auter is currently disabled
			[root@autertestcentos6 ~]# 




[ pass ] auter --enable
    - Check: /var/lib/auter/enabled exists

			[root@autertestcentos6 ~]# auter --enable 
			INFO: auter enabled
			[root@autertestcentos6 ~]# stat /var/lib/auter/enabled
			  File: `/var/lib/auter/enabled'
			  Size: 119       	Blocks: 8          IO Block: 4096   regular file
			Device: ca01h/51713d	Inode: 786700      Links: 1
			Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
			Access: 2018-07-20 09:32:46.521000031 +0000
			Modify: 2018-07-20 09:32:46.522000028 +0000
			Change: 2018-07-20 09:32:46.522000028 +0000
			[root@autertestcentos6 ~]# auter --status
			auter is currently enabled and not running
			[root@autertestcentos6 ~]# 




[ pass ] auter --help
    - Check: same output when running 'auter' without arguments



			[root@autertestcentos6 ~]# auter

			Usage: auter [--enable|--disable|--status] [--prep] [--apply] [--reboot] [--postreboot] [OPTIONS]

			Automatic Update Transaction Execution by Rackspace. A wrapper around cron and yum/dnf/apt to manage system updates with the ability to configure automatic reboots and custom scripts.

			Actions:
			  --enable      Enable auter
			  --disable     Disable auter. Also deletes unused pidfile if it exists
			  --status      Show whether enabled or disabled
			  --prep        Pre-download updates before applying
			  --apply       Apply updates, and reboot if AUTOREBOOT=yes
			  --reboot      Reboot system including pre/post reboot scripts
			  --postreboot  Run post reboot script

			Options:
			  --config=FILE Specify the full path to an auter config file. Defaults to /etc/auter/auter.conf
			  --stdout      Always log to STDOUT, regardless of not having a tty
			  --skip-all-scripts
					Skip the executions of all custom scripts (Default in /etc/auter/*.d/)

			  --skip-scripts-by-phase=PHASE
					Skip the execution of the custom scripts for the specified phase. You can specify myltiple phases.

					Valid Phases: pre-prep, post-prep, pre-apply, post-apply, pre-reboot, post-reboot. 

					Example: --skip-scripts-by-phase="pre-prep,post-apply,pre-reboot"

			  --skip-scripts-by-name=SCRIPTNAME
					Skip specific scripts by name. You can specify myltiple phases. 

					Example: --skip-scripts-by-name="10-configsnap-pre, 20-startApp.sh"

			  --no-wall	If possible, suppress shutdown wall messages in the reboot phase
			  -h, --help    Show this help text
			  -v, --version Show the version

			[root@autertestcentos6 ~]# auter --help

			Usage: auter [--enable|--disable|--status] [--prep] [--apply] [--reboot] [--postreboot] [OPTIONS]

			Automatic Update Transaction Execution by Rackspace. A wrapper around cron and yum/dnf/apt to manage system updates with the ability to configure automatic reboots and custom scripts.

			Actions:
			  --enable      Enable auter
			  --disable     Disable auter. Also deletes unused pidfile if it exists
			  --status      Show whether enabled or disabled
			  --prep        Pre-download updates before applying
			  --apply       Apply updates, and reboot if AUTOREBOOT=yes
			  --reboot      Reboot system including pre/post reboot scripts
			  --postreboot  Run post reboot script

			Options:
			  --config=FILE Specify the full path to an auter config file. Defaults to /etc/auter/auter.conf
			  --stdout      Always log to STDOUT, regardless of not having a tty
			  --skip-all-scripts
					Skip the executions of all custom scripts (Default in /etc/auter/*.d/)

			  --skip-scripts-by-phase=PHASE
					Skip the execution of the custom scripts for the specified phase. You can specify myltiple phases.

					Valid Phases: pre-prep, post-prep, pre-apply, post-apply, pre-reboot, post-reboot. 

					Example: --skip-scripts-by-phase="pre-prep,post-apply,pre-reboot"

			  --skip-scripts-by-name=SCRIPTNAME
					Skip specific scripts by name. You can specify myltiple phases. 

					Example: --skip-scripts-by-name="10-configsnap-pre, 20-startApp.sh"

			  --no-wall	If possible, suppress shutdown wall messages in the reboot phase
			  -h, --help    Show this help text
			  -v, --version Show the version

			[root@autertestcentos6 ~]# 



[ pass ] auter --version
    - Check: prints 'auter VERSION'


		[root@autertestcentos6 ~]# auter --version 
		auter 0.12



#### update manually


updates available: 
		[root@autertestcentos6 ~]# yum check-update
		Loaded plugins: fastestmirror
		Loading mirror speeds from cached hostfile

		gnupg2.x86_64                                                         2.0.14-9.el6_10                                                                 updates
		qemu-img.x86_64                                                       2:0.12.1.2-2.506.el6_10.1                                                       updates
		[root@autertestcentos6 ~]# 


[ pass ] auter --prep
    - Check: prints "INFO: Running with: ./auter --prep Updates downloaded" to stdout
    - Check: /var/lib/auter/last-prep-default contains update info
    - Check: updates downloaded to /var/cache/auter/default
    - Check: pre/post prep scripts ran successfully with messages logged to syslog


		[root@autertestcentos6 ~]# ll /var/cache/auter/default/
		total 0
		[root@autertestcentos6 ~]# auter --prep
		INFO: Running with: /usr/bin/auter --prep
		INFO: Running in an interactive shell, disabling all random sleeps
		INFO: Running Pre-Prep script /etc/auter/pre-prep.d/pre_prep_script
		INFO: Updates downloaded to /var/cache/auter/default
		INFO: Running Post-Prep script /etc/auter/post-prep.d/post_prep_script
		[root@autertestcentos6 ~]# ll /var/cache/auter/default/
		total 2464
		-rw-r--r--. 1 root root 1652484 Jul 13 16:08 gnupg2-2.0.14-9.el6_10.x86_64.rpm
		-rw-r--r--. 1 root root  867784 Jul 13 16:08 qemu-img-0.12.1.2-2.506.el6_10.1.x86_64.rpm
		[root@autertestcentos6 ~]# 

		/var/log/messages show the custom pre and post prep scripts ran: 
		Jul 20 09:35:45 autertestcentos6 auter: INFO: Running with: /usr/bin/auter --prep
		Jul 20 09:35:45 autertestcentos6 auter: INFO: Running in an interactive shell, disabling all random sleeps
		Jul 20 09:35:45 autertestcentos6 auter: INFO: Running Pre-Prep script /etc/auter/pre-prep.d/pre_prep_script
		Jul 20 09:35:45 autertestcentos6 root: custom pre prep script ran
		Jul 20 09:35:48 autertestcentos6 auter: INFO: Updates downloaded to /var/cache/auter/default
		Jul 20 09:35:48 autertestcentos6 auter: INFO: Running Post-Prep script /etc/auter/post-prep.d/post_prep_script
		Jul 20 09:35:48 autertestcentos6 root: custom post prep script ran


[ fail ] auter --apply
    - Check: prints "INFO: Running with: /usr/bin/auter --apply; Applying updates; Updates complete, you may need to reboot for some updates to take effect" to stdout
    - Check: expected updates were applied using 'yum history info' or 'dnf history info'
    - Check: /var/lib/auter/last-update-default contains update info
    - Check: no upates available after running
    - Check: pre/post apply scripts ran successfully, messages logged to syslog
    - Check: no mail is sent to the root user with the stdout from auter


		[root@autertestcentos6 ~]# auter --apply
		INFO: Running with: /usr/bin/auter --apply
		INFO: Running in an interactive shell, disabling all random sleeps
		INFO: Running Pre-Apply script /etc/auter/pre-apply.d/pre_apply_script
		INFO: Applying updates
		INFO: Running Post-Apply script /etc/auter/post-apply.d/pre_apply_script
		INFO: Updates complete (yum Transaction ID : 20). You may need to reboot for some updates to take effect
		INFO: Auter successfully ran at 2018-07-20T09:37:15+0000
		[root@autertestcentos6 ~]# 


		[root@autertestcentos6 ~]# yum history info
		Loaded plugins: fastestmirror
		Transaction ID : 20
		Begin time     : Fri Jul 20 09:37:13 2018
		Begin rpmdb    : 323:60b5a0bc53a34f57665171c764d35b7624bc58a9
		End time       :            09:37:14 2018 (1 seconds)
		End rpmdb      : 323:b4bd86e105436802f019576970020ac9ed2f4eee
		User           : root <root>
		Return-Code    : Success
		Command Line   : install -y /var/cache/auter/default/gnupg2-2.0.14-9.el6_10.x86_64.rpm /var/cache/auter/default/qemu-img-0.12.1.2-2.506.el6_10.1.x86_64.rpm
		Transaction performed with:
		    Installed     rpm-4.8.0-59.el6.x86_64                       @base
		    Installed     yum-3.2.29-81.el6.centos.noarch               @anaconda-CentOS-201703281317.x86_64/6.9
		    Installed     yum-metadata-parser-1.1.2-16.el6.x86_64       @anaconda-CentOS-201703281317.x86_64/6.9
		    Installed     yum-plugin-fastestmirror-1.1.30-41.el6.noarch @base
		Packages Altered:
		    Updated gnupg2-2.0.14-8.el6.x86_64                @base
		    Update         2.0.14-9.el6_10.x86_64             @/gnupg2-2.0.14-9.el6_10.x86_64
		    Updated qemu-img-2:0.12.1.2-2.503.el6_9.6.x86_64  @base
		    Update           2:0.12.1.2-2.506.el6_10.1.x86_64 @/qemu-img-0.12.1.2-2.506.el6_10.1.x86_64
		history info
		[root@autertestcentos6 ~]# 

		[root@autertestcentos6 ~]# yum check-update
		Loaded plugins: fastestmirror
		Loading mirror speeds from cached hostfile
		[root@autertestcentos6 ~]# 


Output file has a different name to what HACKING.md suggest: 

		[root@autertestcentos6 ~]# cat /var/lib/auter/last-update-default
		cat: /var/lib/auter/last-update-default: No such file or directory
		[root@autertestcentos6 ~]# 

		[root@autertestcentos6 ~]# cat /var/lib/auter/last-apply-output-default
		Loaded plugins: fastestmirror
		Setting up Install Process
		Examining /var/cache/auter/default/gnupg2-2.0.14-9.el6_10.x86_64.rpm: gnupg2-2.0.14-9.el6_10.x86_64
		Marking /var/cache/auter/default/gnupg2-2.0.14-9.el6_10.x86_64.rpm as an update to gnupg2-2.0.14-8.el6.x86_64
		Loading mirror speeds from cached hostfile
		Examining /var/cache/auter/default/qemu-img-0.12.1.2-2.506.el6_10.1.x86_64.rpm: 2:qemu-img-0.12.1.2-2.506.el6_10.1.x86_64
		Marking /var/cache/auter/default/qemu-img-0.12.1.2-2.506.el6_10.1.x86_64.rpm as an update to 2:qemu-img-0.12.1.2-2.503.el6_9.6.x86_64
		Resolving Dependencies
		--> Running transaction check
		---> Package gnupg2.x86_64 0:2.0.14-8.el6 will be updated
		---> Package gnupg2.x86_64 0:2.0.14-9.el6_10 will be an update
		---> Package qemu-img.x86_64 2:0.12.1.2-2.503.el6_9.6 will be updated
		---> Package qemu-img.x86_64 2:0.12.1.2-2.506.el6_10.1 will be an update
		--> Finished Dependency Resolution

		Dependencies Resolved

		================================================================================
		 Package  Arch   Version         Repository                                Size
		================================================================================
		Updating:
		 gnupg2   x86_64 2.0.14-9.el6_10 /gnupg2-2.0.14-9.el6_10.x86_64           5.8 M
		 qemu-img x86_64 2:0.12.1.2-2.506.el6_10.1
				                 /qemu-img-0.12.1.2-2.506.el6_10.1.x86_64 1.1 M

		Transaction Summary
		================================================================================
		Upgrade       2 Package(s)

		Total size: 6.9 M
		Downloading Packages:
		Running rpm_check_debug
		Running Transaction Test
		Transaction Test Succeeded
		Running Transaction
		  Updating   : gnupg2-2.0.14-9.el6_10.x86_64                                1/4 
		  Updating   : 2:qemu-img-0.12.1.2-2.506.el6_10.1.x86_64                    2/4 
		  Cleanup    : gnupg2-2.0.14-8.el6.x86_64                                   3/4 
		  Cleanup    : 2:qemu-img-0.12.1.2-2.503.el6_9.6.x86_64                     4/4 
		  Verifying  : 2:qemu-img-0.12.1.2-2.506.el6_10.1.x86_64                    1/4 
		  Verifying  : gnupg2-2.0.14-9.el6_10.x86_64                                2/4 
		  Verifying  : 2:qemu-img-0.12.1.2-2.503.el6_9.6.x86_64                     3/4 
		  Verifying  : gnupg2-2.0.14-8.el6.x86_64                                   4/4 

		Updated:
		  gnupg2.x86_64 0:2.0.14-9.el6_10   qemu-img.x86_64 2:0.12.1.2-2.506.el6_10.1  

		Complete!
		[root@autertestcentos6 ~]# 




[ pass ] auter --reboot
    - Check: reboot scheduled in 2 minutes time
    - Check: prints "INFO: Running with: ./auter --reboot; Rebooting server" followed by shutdown message to stdout
    - Check: 5 minutes after reboot is complete pre/post reboot scripts ran successfully with messages logged to syslog


		[root@autertestcentos6 ~]# auter --reboot
		INFO: Running with: /usr/bin/auter --reboot
		INFO: Running in an interactive shell, disabling all random sleeps
		INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/pre_reboot_script
		INFO: Adding post-reboot-hook to run scripts under /etc/auter/post-reboot.d to /etc/cron.d/auter-postreboot-default
		INFO: Rebooting server
		[root@autertestcentos6 ~]# 
		Broadcast message from root@autertestcentos6.localdomain
			(unknown) at 9:48 ...

		The system is going down for reboot in 2 minutes!
		auter: System reboot to apply updates 


		Jul 20 09:51:40 autertestcentos6 auter: INFO: Running with: /usr/bin/auter --postreboot --config /etc/auter/auter.conf
		Jul 20 09:51:40 autertestcentos6 auter: INFO: Removed post-reboot hook: /etc/cron.d/auter-postreboot-default
		Jul 20 09:56:40 autertestcentos6 auter: INFO: Running Post-Reboot script /etc/auter/post-reboot.d/post_reboot_script
		Jul 20 09:56:40 autertestcentos6 root: custom post reboot script ran

**Comment by Markpayne01** [comment]
#### updates via cron #### 
        [root@autertestcentos6 ~]# crontab -l
        0 11 * * *  /usr/bin/auter --prep --stdout
        30 11 * * * /usr/bin/auter  --apply --stdout
        0 12 * * * /usr/bin/auter  --reboot --stdout
        [root@autertestcentos6 ~]# date 
        Fri Jul 20 10:12:45 UTC 2018
        [root@autertestcentos6 ~]# 

        [root@autertestcentos6 ~]# date 
        Fri Jul 20 10:12:45 UTC 2018
        [root@autertestcentos6 ~]# yum check-update 
        Loaded plugins: fastestmirror
        Loading mirror speeds from cached hostfile

        gnupg2.x86_64                                                         2.0.14-9.el6_10                                                                 updates
        qemu-img.x86_64                                                       2:0.12.1.2-2.506.el6_10.1                                                       updates
        [root@autertestcentos6 ~]# 




[ pass ] auter --prep --stdout
    - Check: updates downloaded to /var/cache/auter/default
    - Check: pre/post prep scripts ran successfully, messages logged to syslog
    - Check: output from auter also mailed to root user on CentOS boxes, output logged to syslog on Fedora systems


        Jul 20 11:00:01 autertestcentos6 auter: INFO: Running with: /usr/bin/auter --prep --stdout
        Jul 20 11:00:01 autertestcentos6 auter: INFO: Running Pre-Prep script /etc/auter/pre-prep.d/pre_prep_script
        Jul 20 11:00:01 autertestcentos6 root: custom pre prep script ran
        Jul 20 11:00:05 autertestcentos6 auter: INFO: Updates downloaded to /var/cache/auter/default
        Jul 20 11:00:05 autertestcentos6 auter: INFO: Running Post-Prep script /etc/auter/post-prep.d/post_prep_script
        Jul 20 11:00:05 autertestcentos6 root: custom post prep script ran

        From root@autertestcentos6.localdomain  Fri Jul 20 11:30:05 2018
        Return-Path: <root@autertestcentos6.localdomain>
        X-Original-To: root
        Delivered-To: root@autertestcentos6.localdomain
        Received: by autertestcentos6.localdomain (Postfix, from userid 0)
            id C0A2AE085C; Fri, 20 Jul 2018 11:30:05 +0000 (UTC)
        From: root@autertestcentos6.localdomain (Cron Daemon)
        To: root@autertestcentos6.localdomain
        Subject: Cron <root@autertestcentos6> /usr/bin/auter  --apply --stdout
        Content-Type: text/plain; charset=UTF-8
        Auto-Submitted: auto-generated
        X-Cron-Env: <LANG=en_US.UTF-8>
        X-Cron-Env: <SHELL=/bin/sh>
        X-Cron-Env: <HOME=/root>
        X-Cron-Env: <PATH=/usr/bin:/bin>
        X-Cron-Env: <LOGNAME=root>
        X-Cron-Env: <USER=root>
        Message-Id: <20180720113005.C0A2AE085C@autertestcentos6.localdomain>


[ pass ] auter --apply --stdout
    - Check: no updates available after running    

          Verified no updates availale No updates available 
                [root@autertestcentos6 ~]# yum check-update
                Loaded plugins: fastestmirror
                Loading mirror speeds from cached hostfile
                [root@autertestcentos6 ~]# 

    - Check: pre/post scripts ran successfully with messages logged to syslog
                Jul 20 11:30:01 autertestcentos6 auter: INFO: Running with: /usr/bin/auter --apply --stdout
                Jul 20 11:30:01 autertestcentos6 auter: INFO: Running Pre-Apply script /etc/auter/pre-apply.d/pre_apply_script
                Jul 20 11:30:01 autertestcentos6 root: custom pre apply script ran
                Jul 20 11:30:01 autertestcentos6 auter: INFO: Applying updates
                Jul 20 11:30:04 autertestcentos6 yum[13277]: Updated: gnupg2-2.0.14-9.el6_10.x86_64
                Jul 20 11:30:05 autertestcentos6 yum[13277]: Updated: 2:qemu-img-0.12.1.2-2.506.el6_10.1.x86_64
                Jul 20 11:30:05 autertestcentos6 auter: INFO: Running Post-Apply script /etc/auter/post-apply.d/pre_apply_script
                Jul 20 11:30:05 autertestcentos6 root: custom post apply script ran
                Jul 20 11:30:05 autertestcentos6 auter: INFO: Updates complete (yum Transaction ID : 22). You may need to reboot for some updates to take effect
                Jul 20 11:30:05 autertestcentos6 auter: INFO: Auter successfully ran at 2018-07-20T11:30:05+0000
      
    - Check: output from Auter also mailed to root user on CentOS boxes, output logged to syslog on Fedora systems

                From root@autertestcentos6.localdomain  Fri Jul 20 11:30:05 2018
                Return-Path: <root@autertestcentos6.localdomain>
                X-Original-To: root
                Delivered-To: root@autertestcentos6.localdomain
                Received: by autertestcentos6.localdomain (Postfix, from userid 0)
                    id C0A2AE085C; Fri, 20 Jul 2018 11:30:05 +0000 (UTC)
                From: root@autertestcentos6.localdomain (Cron Daemon)
                To: root@autertestcentos6.localdomain
                Subject: Cron <root@autertestcentos6> /usr/bin/auter  --apply --stdout
                Content-Type: text/plain; charset=UTF-8
                Auto-Submitted: auto-generated
                X-Cron-Env: <LANG=en_US.UTF-8>
                X-Cron-Env: <SHELL=/bin/sh>
                X-Cron-Env: <HOME=/root>
                X-Cron-Env: <PATH=/usr/bin:/bin>
                X-Cron-Env: <LOGNAME=root>
                X-Cron-Env: <USER=root>
                Message-Id: <20180720113005.C0A2AE085C@autertestcentos6.localdomain>
                Date: Fri, 20 Jul 2018 11:30:01 +0000 (UTC)

                INFO: Running with: /usr/bin/auter --apply --stdout
                INFO: Running Pre-Apply script /etc/auter/pre-apply.d/pre_apply_script
                INFO: Applying updates
                INFO: Running Post-Apply script /etc/auter/post-apply.d/pre_apply_script
                INFO: Updates complete (yum Transaction ID : 22). You may need to reboot for some updates to take effect
                INFO: Auter successfully ran at 2018-07-20T11:30:05+0000

                [root@autertestcentos6 ~]# yum history info 22 
                Loaded plugins: fastestmirror
                Transaction ID : 22
                Begin time     : Fri Jul 20 11:30:04 2018
                Begin rpmdb    : 323:60b5a0bc53a34f57665171c764d35b7624bc58a9
                End time       :            11:30:05 2018 (1 seconds)
                End rpmdb      : 323:b4bd86e105436802f019576970020ac9ed2f4eee
                User           : root <root>
                Return-Code    : Success
                Command Line   : install -y /var/cache/auter/default/gnupg2-2.0.14-9.el6_10.x86_64.rpm /var/cache/auter/default/qemu-img-0.12.1.2-2.506.el6_10.1.x86_64.rpm
                Transaction performed with:
                    Installed     rpm-4.8.0-59.el6.x86_64                       @base
                    Installed     yum-3.2.29-81.el6.centos.noarch               @anaconda-CentOS-201703281317.x86_64/6.9
                    Installed     yum-metadata-parser-1.1.2-16.el6.x86_64       @anaconda-CentOS-201703281317.x86_64/6.9
                    Installed     yum-plugin-fastestmirror-1.1.30-41.el6.noarch @base
                Packages Altered:
                    Updated gnupg2-2.0.14-8.el6.x86_64                @base
                    Update         2.0.14-9.el6_10.x86_64             @/gnupg2-2.0.14-9.el6_10.x86_64
                    Updated qemu-img-2:0.12.1.2-2.503.el6_9.6.x86_64  @base
                    Update           2:0.12.1.2-2.506.el6_10.1.x86_64 @/qemu-img-0.12.1.2-2.506.el6_10.1.x86_64
                history info



[ pass ] auter --reboot --stdout
    - Check: server rebooted after 2 minutes

    Cronjob for --reboot ran at 12, system rebooted 2 minutes later
        [root@autertestcentos6 ~]# last | grep reboot 
        reboot   system boot  2.6.32-754.2.1.e Fri Jul 20 12:02 - 12:14  (00:12)    
        reboot   system boot  2.6.32-754.2.1.e Fri Jul 20 09:51 - 12:02  (02:10)  
        
    - Check: pre/post scripts ran successfully

        Pre reboot: 
        Jul 20 12:00:01 autertestcentos6 auter: INFO: Running with: /usr/bin/auter --reboot --stdout
        Jul 20 12:00:01 autertestcentos6 auter: INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/pre_reboot_script
        Jul 20 12:00:01 autertestcentos6 root: custom pre reboot script ran
        Jul 20 12:00:01 autertestcentos6 auter: INFO: Adding post-reboot-hook to run scripts under /etc/auter/post-reboot.d to /etc/cron.d/auter-postreboot-default
        Jul 20 12:00:01 autertestcentos6 auter: INFO: Rebooting server

        Post Reboot: 
        Jul 20 12:03:03 autertestcentos6 auter: INFO: Running with: /usr/bin/auter --postreboot --config /etc/auter/auter.conf
        Jul 20 12:03:03 autertestcentos6 auter: INFO: Removed post-reboot hook: /etc/cron.d/auter-postreboot-default
        Jul 20 12:08:03 autertestcentos6 auter: INFO: Running Post-Reboot script /etc/auter/post-reboot.d/post_reboot_script
        Jul 20 12:08:03 autertestcentos6 root: custom post reboot script ran


    - Check: output from Auter also mailed to the root user on CentOS, output logged to syslog on Fedora

        From root@autertestcentos6.localdomain  Fri Jul 20 12:00:02 2018
        Return-Path: <root@autertestcentos6.localdomain>
        X-Original-To: root
        Delivered-To: root@autertestcentos6.localdomain
        Received: by autertestcentos6.localdomain (Postfix, from userid 0)
            id F06B6E245B; Fri, 20 Jul 2018 12:00:01 +0000 (UTC)
        From: root@autertestcentos6.localdomain (Cron Daemon)
        To: root@autertestcentos6.localdomain
        Subject: Cron <root@autertestcentos6> /usr/bin/auter  --reboot --stdout
        Content-Type: text/plain; charset=UTF-8
        Auto-Submitted: auto-generated
        X-Cron-Env: <LANG=en_US.UTF-8>
        X-Cron-Env: <SHELL=/bin/sh>
        X-Cron-Env: <HOME=/root>
        X-Cron-Env: <PATH=/usr/bin:/bin>
        X-Cron-Env: <LOGNAME=root>
        X-Cron-Env: <USER=root>
        Message-Id: <20180720120001.F06B6E245B@autertestcentos6.localdomain>
        Date: Fri, 20 Jul 2018 12:00:01 +0000 (UTC)

        INFO: Running with: /usr/bin/auter --reboot --stdout
        INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/pre_reboot_script
        INFO: Adding post-reboot-hook to run scripts under /etc/auter/post-reboot.d to /etc/cron.d/auter-postreboot-default
        INFO: Rebooting server

**Comment by reaperzn** [comment]
Thanks @markp1989 Are you still testing this further or has this been completed?

**Comment by rhodesn** [comment]
# Test 4: Manual process - Modified config [ PASS ]
### Changes made:

```
sed -i 's/AUTOREBOOT.*$/AUTOREBOOT="yes"/g' /etc/auter/auter.conf
sed -i 's/ONLYINSTALLFROMPREP.*$/ONLYINSTALLFROMPREP="yes"/g' /etc/auter/auter.conf
```

### Config settings

```
$ egrep -v "^$|^#" /etc/auter/auter.conf`
CONFIGSET="default"
AUTOREBOOT="yes"
PACKAGEMANAGEROPTIONS=""
PREDOWNLOADUPDATES="yes"
ONLYINSTALLFROMPREP="yes"
MAXDELAY="60"
PACKAGEMANAGERLOCKWAITTIME="60"
PACKAGEMANAGERLOCKRETRIES="5"
PREPREPSCRIPTDIR="/etc/auter/pre-prep.d"
POSTPREPSCRIPTDIR="/etc/auter/post-prep.d"
PREAPPLYSCRIPTDIR="/etc/auter/pre-apply.d"
POSTAPPLYSCRIPTDIR="/etc/auter/post-apply.d"
PREREBOOTSCRIPTDIR="/etc/auter/pre-reboot.d"
POSTREBOOTSCRIPTDIR="/etc/auter/post-reboot.d"
```

2) Prepare custom scripts: Execute:

```
echo 'logger auter custom pre prep script ran' > /etc/auter/pre-prep.d/pre_prep_script
echo 'logger auter custom post prep script ran' > /etc/auter/post-prep.d/post_prep_script
echo 'logger auter custom pre apply script ran' > /etc/auter/pre-apply.d/pre_apply_script
echo 'logger auter custom post apply script ran' > /etc/auter/post-apply.d/pre_apply_script
echo 'logger auter custom pre reboot script ran' > /etc/auter/pre-reboot.d/pre_reboot_script
echo 'logger auter custom post reboot script ran' > /etc/auter/post-reboot.d/post_reboot_script
chmod +x /etc/auter/*.d/*script
```

3) Execute: `auter --prep`

- __[ pass ]__ prints the following block to stdout:

```
INFO: Running with: /usr/bin/auter --prep
INFO: Running in an interactive shell, disabling all random sleeps
INFO: Running Pre-Prep script /etc/auter/pre-prep.d/pre_prep_script
INFO: Updates downloaded
INFO: Running Post-Prep script /etc/auter/post-prep.d/post_prep_script
```

- __[ pass ]__ **_/var/lib/auter/last-prep-output-default_** contains yum download-only output
- __[ pass ]__ updates downloaded to **_/var/cache/auter/default/_**
- __[ pass ]__ pre/post prep scripts ran successfully with messages logged to syslog

##### Output from prep:

```
root@centos6:~ # auter --prep
INFO: Running with: /usr/bin/auter --prep
INFO: Running in an interactive shell, disabling all random sleeps
INFO: Running Pre-Prep script /etc/auter/pre-prep.d/pre_prep_script
INFO: Updates downloaded to /var/cache/auter/default
INFO: Running Post-Prep script /etc/auter/post-prep.d/post_prep_script
```

4) Execute `auter --apply`
- __[ pass ]__ prints the following block to stdout:

```
INFO: Running with: /usr/bin/auter --apply
INFO: Running in an interactive shell, disabling all random sleeps
INFO: Running Pre-Apply script /etc/auter/pre-apply.d/pre_apply_script
INFO: Applying updates
INFO: Running Post-Apply script /etc/auter/post-apply.d/pre_apply_script
INFO: Updates complete (yum Transaction ID : <ID>). You may need to reboot for some updates to take effect
INFO: Auter successfully ran at <TIMESTAMP>
INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/pre_reboot_script
INFO: Adding post-reboot-hook to run scripts under /etc/auter/post-reboot.d to /etc/cron.d/auter-postreboot-default
INFO: Rebooting server
```

- __[ pass ]__ expected updates were applied. Check **_/var/log/apt/history.log_** or **_/var/log/yum.log_**
- __[ pass ]__ **_/var/lib/auter/last-apply-output-default_** contains update info
- __[ pass ]__ no upates available after running. Check `yum update <<<n` or `apt-get --just-print upgrade`
- __[ pass ]__ pre/post apply scripts ran successfully, messages logged to syslog
- __[ pass ]__ no mail is sent to the root user with the stdout from auter

##### Output from apply:

```
root@centos6:~ # auter --apply
INFO: Running with: /usr/bin/auter --apply
INFO: Running in an interactive shell, disabling all random sleeps
INFO: Running Pre-Apply script /etc/auter/pre-apply.d/pre_apply_script
INFO: Applying updates
INFO: Running Post-Apply script /etc/auter/post-apply.d/pre_apply_script
INFO: Updates complete (yum Transaction ID : 41). You may need to reboot for some updates to take effect
INFO: Auter successfully ran at 2018-08-04T11:25:14+0000
INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/pre_reboot_script
INFO: Adding post-reboot-hook to run scripts under /etc/auter/post-reboot.d to /etc/cron.d/auter-postreboot-default
INFO: Rebooting server
```

5) Execute 'auter --reboot` __( AUTOMATIC: AUTOREBOOT="yes")__

- __[ pass ]__ reboot scheduled in 2 minutes time
- __[ pass ]__ pre reboot script ran successfully, messages logged to syslog
- __[ pass ]__ **_/etc/cron.d/auter-postreboot-default_** contains `@reboot root /usr/bin/auter --postreboot --config /etc/auter/auter.conf`
- __[ pass ]__ **_/etc/cron.d/auter-postreboot-default_** has the correct permissions: `root:root:0644`

6) After server has rebooted:

- __[ pass ]__ Server actually rebooted: Execute `uptime`
- __[ pass ]__ **_ /etc/cron.d/auter-postreboot-default _** has been removed after the has fully completed the startup process
- __[ pass ]__ post reboot script ran successfully, messages logged to syslog

##### Output from reboot:

```
Aug  4 11:27:09 centos6 auter: INFO: Running with: /usr/bin/auter --reboot
Aug  4 11:27:09 centos6 auter: INFO: Running in an interactive shell, disabling all random sleeps
Aug  4 11:27:09 centos6 auter: INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/pre_reboot_script
Aug  4 11:27:09 centos6 root: auter custom pre reboot script ran
Aug  4 11:27:09 centos6 auter: INFO: Adding post-reboot-hook to run scripts under /etc/auter/post-reboot.d to /etc/cron.d/auter-postreboot-default
Aug  4 11:27:09 centos6 auter: INFO: Rebooting server
Aug  4 11:30:11 centos6 auter: INFO: Running with: /usr/bin/auter --postreboot --config /etc/auter/auter.conf
Aug  4 11:30:11 centos6 auter: INFO: Removed post-reboot hook: /etc/cron.d/auter-postreboot-default
Aug  4 11:35:11 centos6 auter: INFO: Running Post-Reboot script /etc/auter/post-reboot.d/post_reboot_script
Aug  4 11:35:11 centos6 root: auter custom post reboot script ran
```

**Comment by rhodesn** [comment]
This is pass, closing.

**Comment by rhodesn** [comment]
Just to clarify, the failure re the file name is an issue with the hacking document which is not a blocker to this release.
