### ISSUE TITLE
Ubuntu 'apply' fails with cron

### ISSUE THREAD

**Issue by popindavibe** [rackerlabs/auter#190]
During auter testing on Ubuntu 16.04, running `/usr/sbin/auter --apply` through `/etc/cron.d/auter` would fail.
Two issues were identified on that particular test.

1) auter is running apt without setting environment variable `DEBIAN_FRONTEND=noninteractive`, which leads to errors if any package is subject to opening a Dialog box in interactive mode:
```
Trying to update
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
E: Sub-process /usr/bin/dpkg returned an error code (2)
```
2) When running from `/etc/cron.d/auter` environment variable `PATH` does not contain required `/sbin:/usr/sbin:/usr/local/sbin`
```
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
```

**Comment by reaperzn** [comment]
Resolved
