### ISSUE TITLE
Remove the 01-spellcheck.sh test script

### ISSUE THREAD

**Issue by rhodesn** [rackerlabs/auter#202]
The script is currently not working (see below) due to travis missing the aspell-en package. It also feels like unnecessary effort having to include all variables etc in `.aspell_auter_dictionary`. People can and should correct spelling mistakes as and when they are found.

```
$ docker exec auter-test /auter/tests/01-spellcheck.sh
Error: No word lists can be found for the language "en_US".
Error: No word lists can be found for the language "en_US".
Error: No word lists can be found for the language "en_US".
Error: No word lists can be found for the language "en_US".
```

Personally I vote to remove the test - people can run whatever spell checker they want locally before submitting PRs for config/man pages.

**Comment by reaperzn** [comment]
We should rather fix the issues or at least implement some form of spell checker as a standard automated test. There has been a history of spelling mistakes in man pages, help output, comments and even some logs which have previously been missed.
