### ISSUE TITLE
Add final STATUS line to 'output files' i.e. /var/lib/auter/last-{phase}-output-default 

### ISSUE THREAD

**Issue by mark-hyde** [rackerlabs/auter#213]
I've a script which I run across multiple servers to determine the success/failure status of each phase of auter for reporting purposes.

/var/lib/auter/last-{phase}-output-default  is generated for each phase of auter, and overwritten with the output from the latest run each time.

We wish to be able to determine, by examining this file, whether or not this specific phase of the auter run has succeeded or failed at the latest attempt. 
---

The following approaches are currently possible but have downsides:
A - grep for the auter logs in /var/log/messages. Look for 'auter --{phase} ' and then look for any 'ERROR' which follows.
  - If there have been re-runs of e.g. the auter --prep phase after fixing an issue it's tricky to determine whether an ERROR if for the latest or previous iterations
 - If a prep and an apply happen shortly after each other - again disambiguating whether an ERROR message belongs to which phase is tricky
 - It can be done with sed/awk/etc, but is open to error and bad assumptions

B - find the datestamp at the top of the output file, look for ERRORs  in the system log at that time.
 - The timestamp in the file records the start of the auter run, the timestamp of the ERROR in the system log records some time later (maybe only a few seconds or minutes) - things could be done to e.g. only look for ERRORs in the same hour or minute or day, but this leads to unreliability should the auter run cross a time boundary. We could try to get clever with converting log timestamps to seconds since epoch, and then do something with that, but it's still not going to be that reliable.

C - grep -i ERROR in the 'output file' for that phase
- It has a timestamp at the top which we can use
- We can look for variations of 'Error|error|ERROR' etc in the log and report a fail if it finds it.
- False negatives if there are any rpms being installed which contain the word 'error' in them.
- We could look for specific error strings such as 'Error Downloading Packages' but this might miss other error conditions.

---

Instead could you add a status line to the end of the /var/lib/auter/last-{phase}-output-default files with an easily parse-able status

**Comment by rhodesn** [comment]
Would something in the format:
```
STATUS:FAILED:Small description of state
//
STATUS:SUCCESS:Small description of state
```
On the last line work for you?

**Comment by mark-hyde** [comment]
That would be super!

**Comment by rhodesn** [comment]
I've popped a quick PR in #214. I went with a SUCCESS status for no package updates available as everything technically ran correctly. Let me know what you think, and if you want any changes made.

**Comment by rhodesn** [comment]
Closing now that #214 has been merged in.
