### ISSUE TITLE
Auter not available on CentOS 8?

### ISSUE THREAD

**Issue by kriansa** [rackerlabs/auter#235]
Recently I've upgraded to CentOS 8 and unfortunately auter is not available on `epel`. Are there any plans for packaging it to RHEL/CentOS 8? Or is it just me that didn't find it?

```
[root@centos8 ~]# dnf repoquery --repo epel auter
Last metadata expiration check: 0:10:47 ago on Mon 09 Dec 2019 02:28:50 AM UTC.
[root@centos8 ~]#
```

**Comment by rhodesn** [comment]
@kriansa thank you for the reminder - I just need to push the package to the EL8 EPEL repo. I'll get this done ASAP and will update here.

**Comment by nrhodes91** [comment]
@kriansa thank you for the reminder - I just need to push the package to the EL8 EPEL repo. I'll get this done ASAP and will update here.

**Comment by rhodesn** [comment]
FYI the package is currently pending movement to the epel-testing repo. Once this is complete you can install it by enabling that repo. It should move to stable not long after if I can get some karma on https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-fac3ef5d5a.

**Comment by rhodesn** [comment]
Happy to announce that Auter is now packaged and available in the EPEL8 repo.

**Comment by kriansa** [comment]
Awesome, @nrhodes91 ! Thanks for acting so quickly on this!
