### ISSUE TITLE
Ubuntu  support

### ISSUE THREAD

**Issue by lil-cain** [rackerlabs/auter#24]
Heya,

It'd be super good if this supported ubuntu as well!

**Comment by reaperzn** [comment]
This may actually be possible by moving some of the functions to separate scripts. 
The only functions that require changes are prepare_updates and apply_updates. We could make separate distribution specific "modules" ie:
in the auter script we adjust the call to the prepare_updates finction to:
`[[ "${PREP}" ]] && . ${FUNCTIONDIR}/auter.module prepare_updates`
We then have the code from the current prepare_updates function saved in ${FUNCTIONDIR}/auter.module

That way we have distribution specific code in a separate file and only universal code in the main auter script. The best part of this is that if we implement this in the above mentioned way, all the variables are automatically passed both ways (from the parent script to the child script and also from the child script back to the parent script) if needed.

@piersc This does however mean that we abandon the idea of a separate package and the opportunity of using dauter as the name.

Does anyone have any major concerns or thoughts on this approach?

**Comment by reaperzn** [comment]
I have now prepared an initial attempt at the apt-get module in #51 @lil-cain It would be great if you could test and review that PR

**Comment by reaperzn** [comment]
This has now been completed in #32 and #51
