### ISSUE TITLE
auter-updater.com site does not support https

### ISSUE THREAD

**Issue by aral** [rackerlabs/auter#241]
https://auter-updater.com (404)

Would definitely give more of an impression that the project was maintained/up-to-date/trustworthy if it did.

**Comment by mark-hyde** [comment]
I'll admit I don't know who owns that domain, it was most likely setup by the previous maintainers at some point.
We probably need to remove any references to the site from any docs. Do you know of any places which link to it?

**Comment by mark-hyde** [comment]
The site is up and running again having spoken to Paolo, but it's not officially linked to the project and as far as we can tell there's no links to it from within anything in the project. I don't think there's any intent to have https on the site.
