### ISSUE TITLE
Request Maintainer status

### ISSUE THREAD

**Issue by mark-hyde** [rackerlabs/auter#244]
Hi Nick, Paulo, 

As far as I'm aware there's no-one currently within Rackspace currently maintaining this project, but it is still used internally for some customers.
Would it be possible to get commit privileges and me to the list of maintainers for this project as the team I'm in would like to help take on this role within Rackspace?

Regards
Mark

**Comment by rhodesn** [comment]
@mark-hyde I had my access removed a long time ago.

**Comment by mark-hyde** [comment]
Ah OK - I'll ask the rackerlabs organisation admins to give me access then!

**Comment by mark-hyde** [comment]
I have access now - Do you and Paulo want to have outside collaborator status on the repo?
@nrhodes91 @reaperzn

**Comment by rhodesn** [comment]
@mark-hyde I'm glad to hear you managed to get access. I don't think it makes sense for me to have any access/status these days, but thanks.
