### ISSUE TITLE
Any way to send email?

### ISSUE THREAD

**Issue by dantahoua** [rackerlabs/auter#248]
Hello.
This tool is great but I do not see any way of sending email when it is finished or before reboot with the list of upgraded package?
Seems there was a contrib, but it is not included...
Any idea?

**Comment by mark-hyde** [comment]
Hi,
You can add a `hook` script for any of the different phases which could be used to send an email. 

e.g. If you wanted to send an email after running `auter --apply` then you would create a script and add it to the `/etc/auter/post-apply.d` directory and it would be run just after the packages have been installed, but prior to any configured reboots.

You could send the contents of `/var/lib/auter/last-apply-output-default` which is the output from the most recent `apply` phase.

Hope that helps

**Comment by dantahoua** [comment]
Thanks that is perfect! :)
