### ISSUE TITLE
dnf issue with ${DOWNLOADDIR}/${CONFIGSET}

### ISSUE THREAD

**Issue by reaperzn** [rackerlabs/auter#29]
When using the following options in combination we have a slight issue (This is the default options at install time) 
```
PREDOWNLOADUPDATES="yes"
ONLYINSTALLFROMPREP="no"
```

The problem is that the ${DOWNLOADDIR}/${CONFIGSET} directory is only created if ONLYINSTALLFROMPREP is set to yes (See line 333)
```
if [[ "${ONLYINSTALLFROMPREP}" == "yes" ]]; then
  if [[ ! -d "${DOWNLOADDIR}/${CONFIGSET}" ]]; then
    install -m 755 -o root -g root -d ${DOWNLOADDIR}/${CONFIGSET}
  elif [[ $(stat -c %G%U%a "${DOWNLOADDIR}") != rootroot[0-9][0-9][0,1,4,5] ]]; then
    logit "ERROR: ${DOWNLOADDIR}/${CONFIGSET} does not have the correct permissions."
    quit 3
  fi
fi
```
However in the prep function, if PREDOWNLOADUPDATES==yes and PACKAGE_MANAGER == dnf  we have the following line:
```
[[ "${PACKAGE_MANAGER}" == "dnf" ]] && find /var/cache/dnf -name *.rpm -exec mv {} ${DOWNLOADDIR}/${CONFIGSET} \;
```

In the default config case we are moving all rpms to ${DOWNLOADDIR}/${CONFIGSET} however that directory is never created so we land up with the following situation:

Before I run prep:
```
# dnf check-update 
Last metadata expiration check: 2:29:07 ago on Tue Jan 24 08:39:37 2017.

openssl.x86_64                                                      1:1.0.2j-3.fc24                                                 updates
openssl-libs.x86_64                                                 1:1.0.2j-3.fc24                                                 updates

# ll /var/cache/auter/
total 0
```

I then run prep:
```
# auter --prep
INFO: Running with: /usr/bin/auter --prep
INFO: Running in an interactive shell, disabling all random sleeps
INFO: Updates downloaded
```

At this point the /var/cache/auter/default directory should have been created and the rmps moved to that directory however because the directory was not created we have the following file that was created:
```
# ll /var/cache/auter/default 
-rw-r--r--. 1 root root 1258970 Jan 24 11:09 /var/cache/auter/default

# file /var/cache/auter/default
/var/cache/auter/default: RPM v3.0 bin i386/x86_64 openssl-libs-1:1.0.2j-3.fc24
```

The update still runs as expected however this is not the expected behavior and should be fixed.

**Comment by reaperzn** [comment]
There are 2 possible fixes here:
1) We could change line 331 from ONLYINSTALLFROMPREP to PREDOWNLOADUPDATES
This would mean that we ALWAYS create that directory even if we are not using it. 

2) We could add the following before after line 122 to ensure this is created
```
[[ ! -d "${DOWNLOADDIR}/${CONFIGSET}" ]] && install -m 755 -o root -g root -d ${DOWNLOADDIR}/${CONFIGSET}
```

**Comment by piersc** [comment]
IMO the right thing to do here is to wrap line 122 in a block so its only run if ONLYINSTALLFROMPREP=yes.
