### ISSUE TITLE
Auter post script doesn't run if updates fail

### ISSUE THREAD

**Issue by Beerey** [rackerlabs/auter#52]
Per title. There's a quit if updates weren't applied successfully which gets triggered before the post script is able to run:

```
    if [[ "${HISTORY_BEFORE}" == "${HISTORY_AFTER}" ]]; then
      logit "ERROR: Updates failed. Exiting."
      quit 3
fi

<post script code>
```

There's no indication that this would happen in the doco and logically doesn't make much sense - if updates fail for some reason, but you've disabled monitoring / stopped services in the pre scripts, you're in a bad shape.

The naive solution is to just re-order the code to run the post script before the success of the update is checked, but maybe a potential improvement would be to pass the status of the update into the post script as $1 so the script can then potentially do different things depending on whether the update failed or not.

**Comment by piersc** [comment]
fixed in https://github.com/rackerlabs/auter/commit/1fc129e14f73e36c041141aa0a676dd2bfa8e17a
