### ISSUE TITLE
Pre and post prep scripts

### ISSUE THREAD

**Issue by reaperzn** [rackerlabs/auter#58]
I finally remembered the purpose for #17 and #19 

So can we please add at least a post-prep script but preferably a pre-prep script too. The main purpose of this would be to take an action based on the patches that were downloaded. 

Example:
Patches are downloaded on Monday: 
   - post-prep script does a directory listing of /var/cache/auter/{{PROFILE}}/ and emails the list of patches to be applied to the administrator.

**Comment by piersc** [comment]
Ok, seems fair. As an aside, yum-cron has built in functionality to send email notifications.

**Comment by piersc** [comment]
Fixed in https://github.com/rackerlabs/auter/commit/bdcbf933031aa12d7d822a3ae3ae193ac003705e
