### ISSUE TITLE
Auter should report the date/time that it completed

### ISSUE THREAD

**Issue by samjsharpe** [rackerlabs/auter#62]
Tools, including [auter-audit.sh](https://github.com/rackerlabs/auter-manager/blob/master/reporter/auter-audit.sh) would like to report the date that Auter last run. It would be much easier to do this in a standard way if Auter reported (in ISO8601 format) the date/time it completed.

e.g. instead of this:
```
# zgrep -h "auter.*complete" /var/log/messages-20170723.gz
Jul 20 00:09:18 test-server auter: INFO: Updates complete (yum Transaction ID : 44). You may need to reboot for some updates to take effect
```

We should have something like this:
```
Jul 20 00:09:18 test-server auter: INFO: Updates complete (yum Transaction ID : 44). You may need to reboot for some updates to take effect. DATETIME=2017-07-20T00:09:18
```

That way tools can extract the DATETIME from the log, rather than relying on what logging format the server has set in syslog for its date.

**Comment by reaperzn** [comment]
Done, Dusted and Closed
